-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 19:08:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommercedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommercedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommercedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommercedb` ;

-- -----------------------------------------------------
-- Table `ecommercedb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`clientes` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `TipoCliente` ENUM('Pessoa Física', 'Pessoa Jurídica') NULL DEFAULT NULL,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Endereco` VARCHAR(255) NULL DEFAULT NULL,
  `CPF` VARCHAR(14) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`ClienteID`),
  UNIQUE INDEX `CPF` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ` (`CNPJ` ASC) VISIBLE,
  INDEX `idx_numero_pessoas_departamento` (`TipoCliente` ASC, `Nome` ASC) VISIBLE,
  INDEX `idx_departamento_cidade` (`Endereco` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`pedidos` (
  `PedidoID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NULL DEFAULT NULL,
  `DataPedido` DATETIME NULL DEFAULT NULL,
  `Status` ENUM('Pendente', 'Processando', 'Enviado', 'Entregue') NULL DEFAULT NULL,
  PRIMARY KEY (`PedidoID`),
  INDEX `idx_empregados_departamento` (`ClienteID` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `ecommercedb`.`clientes` (`ClienteID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`entregas` (
  `EntregaID` INT NOT NULL AUTO_INCREMENT,
  `PedidoID` INT NULL DEFAULT NULL,
  `Status` ENUM('Pendente', 'Processando', 'Enviado', 'Entregue') NULL DEFAULT NULL,
  `CodigoRastreio` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`EntregaID`),
  INDEX `PedidoID` (`PedidoID` ASC) VISIBLE,
  CONSTRAINT `entregas_ibfk_1`
    FOREIGN KEY (`PedidoID`)
    REFERENCES `ecommercedb`.`pedidos` (`PedidoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`produtos` (
  `ProdutoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Descricao` TEXT NULL DEFAULT NULL,
  `Preco` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ProdutoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`estoque` (
  `EstoqueID` INT NOT NULL AUTO_INCREMENT,
  `ProdutoID` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`EstoqueID`),
  INDEX `fk_estoque_produtos` (`ProdutoID` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produtos`
    FOREIGN KEY (`ProdutoID`)
    REFERENCES `ecommercedb`.`produtos` (`ProdutoID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`fornecedores` (
  `FornecedorID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`FornecedorID`),
  INDEX `fk_fornecedores_clientes` (`ClienteID` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedores_clientes`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `ecommercedb`.`clientes` (`ClienteID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`itenspedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`itenspedido` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `PedidoID` INT NULL DEFAULT NULL,
  `ProdutoID` INT NULL DEFAULT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  `PrecoUnitario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `PedidoID` (`PedidoID` ASC) VISIBLE,
  INDEX `ProdutoID` (`ProdutoID` ASC) VISIBLE,
  CONSTRAINT `itenspedido_ibfk_1`
    FOREIGN KEY (`PedidoID`)
    REFERENCES `ecommercedb`.`pedidos` (`PedidoID`),
  CONSTRAINT `itenspedido_ibfk_2`
    FOREIGN KEY (`ProdutoID`)
    REFERENCES `ecommercedb`.`produtos` (`ProdutoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`pagamentos` (
  `PagamentoID` INT NOT NULL AUTO_INCREMENT,
  `PedidoID` INT NULL DEFAULT NULL,
  `FormaPagamento` VARCHAR(100) NULL DEFAULT NULL,
  `Valor` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`PagamentoID`),
  INDEX `PedidoID` (`PedidoID` ASC) VISIBLE,
  CONSTRAINT `pagamentos_ibfk_1`
    FOREIGN KEY (`PedidoID`)
    REFERENCES `ecommercedb`.`pedidos` (`PedidoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommercedb`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`vendedores` (
  `VendedorID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`VendedorID`),
  UNIQUE INDEX `ClienteID_UNIQUE` (`ClienteID` ASC) VISIBLE,
  CONSTRAINT `fk_vendedores_clientes`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `ecommercedb`.`clientes` (`ClienteID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `ecommercedb` ;

-- -----------------------------------------------------
-- procedure ManipularDados
-- -----------------------------------------------------

DELIMITER $$
USE `ecommercedb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ManipularDados`(
    IN opcao INT,
    IN cliente_id INT,
    IN nome_cliente VARCHAR(100),
    IN email_cliente VARCHAR(100),
    IN endereco_cliente VARCHAR(255),
    IN cpf_cliente VARCHAR(14),
    IN cnpj_cliente VARCHAR(18)
)
BEGIN
    CASE opcao
        WHEN 1 THEN
            -- Inserção de dados
            INSERT INTO clientes (Nome, Email, Endereco, CPF, CNPJ)
            VALUES (nome_cliente, email_cliente, endereco_cliente, cpf_cliente, cnpj_cliente);
        
        WHEN 2 THEN
            -- Atualização de dados
            UPDATE clientes
            SET Nome = nome_cliente, Email = email_cliente, Endereco = endereco_cliente, CPF = cpf_cliente, CNPJ = cnpj_cliente
            WHERE ClienteID = cliente_id;
        
        WHEN 3 THEN
            -- Remoção de dados
            DELETE FROM clientes
            WHERE ClienteID = cliente_id;
            
        ELSE
            -- Opção inválida
            SELECT 'Opção inválida';
    END CASE;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
